name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 9.0.4 for x64
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          architecture: x64
      - name: Run Build
        run: |
          mvn clean package
